apiVersion: v1
kind: Service
metadata:
  name: curl-service
spec:
  selector:
    app: curl  # Label selector for pods to expose
  ports:
  - protocol: TCP
    port: 80  # Port exposed by the service
    targetPort: 8080  # Port where your application is running inside the container
